### ISSUE TITLE
GAE

### ISSUE THREAD

**Issue by tfolkman** [higgsfield/RL-Adventure-2#6]
Hi, 

Thanks for all the great code. I was working through GAE and couldn't figure out why you add back values[step] in this line?

returns.insert(0, gae + values[step])

This doesn't seem to be part of the algorithm proposed in the paper?

Thank you!

**Comment by makdoudN** [comment]
Hi

I may miss something but It seems that the discounted sum of td residual is a valid choice for estimated g (at least empirically). 
It is quite misleading to call it GAE in this case. 
Just use returns.insert(0, gae) if you want to use GAE in the "standart form".

**Comment by tfolkman** [comment]
Yeah - I eventually figured that out. Thanks!

**Comment by Evil-Incorporated** [comment]
Another thing, why are you are using advantage = returns - value, shoudn't the returns be the advantage function?

**Comment by jsrimr** [comment]
> Another thing, why are you are using advantage = returns - value, shoudn't the returns be the advantage function?

It's because returns were not actually return but were gae+values.
returns.insert(0, gae + values[step])

So, to figure out advantage, you need to get rid of values
